### ISSUE TITLE
JS Error with a live key

### ISSUE THREAD

**Issue by praharshbhatt** [MarcinusX/flutter_stripe_demo#2]
When running this in iOS simulator with a live key, it gives error:
```
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'var stripe = Stripe('<Stripe key>');

stripe.redirectToCheckout({
  sessionId: 'cs_live_a0tCIGOAnW9bEG4L0gNpHHwEvN9Rg22CrV21lYQIvSvn2l7SlhzvBgTKiq'
}).then(function (result) {
  result.error.message = 'Error'
});
'
Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=IntegrationError: Live Stripe.js integrations must use HTTPS. For more information: https://stripe.com/docs/security/guide#tls, WKJavaScriptExceptionColumnNumber=184970, WKJavaScriptExceptionSourceURL=https://js.stripe.com/v3/, NSLocalizedDescription=A JavaScript exception occurred}, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:1<…>
```

**Comment by MarcinusX** [comment]
Hi :)
Can you share the widget code you're using?

**Comment by praharshbhatt** [comment]
Sure!

stripe_checkout_session.dart:
```
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:kinderpass_app/common/common.dart';
import 'package:webview_flutter/webview_flutter.dart';

class StripeCheckoutSession extends StatefulWidget {
  final String listingId, sessionId;

  StripeCheckoutSession(this.listingId, this.sessionId);

  @override
  StripeCheckoutSessionState createState() => StripeCheckoutSessionState();
}

class StripeCheckoutSessionState extends State<StripeCheckoutSession> {
  WebViewController _webViewController;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      body: WebView(
        initialUrl: initialUrl,
        javascriptMode: JavascriptMode.unrestricted,
        onWebViewCreated: (webViewController) => _webViewController = webViewController,
        onPageFinished: (String url) {
          if (url == initialUrl) {
            _redirectToStripe(widget.sessionId);
          }
        },
        navigationDelegate: (NavigationRequest request) {
          print(request);
          print(request.url);
          if (request.url.startsWith('http://mykinderpass.com') ||
              request.url.startsWith('http://staging.mykinderpass.com') ||
              request.url.startsWith('https://mykinderpass.com') ||
              request.url.startsWith('https://staging.mykinderpass.com')) {
            Navigator.of(context).pop();
            //Navigator.of(context).pushReplacementNamed('/success');
          } else if (request.url.startsWith('http://mykinderpass/cancel')) {
            Navigator.of(context).pop();
            //Navigator.of(context).pushReplacementNamed('/cancel');
          }
          return NavigationDecision.navigate;
        },
      ),
    );
  }

  String get initialUrl => 'data:text/html;base64,${base64Encode(Utf8Encoder().convert(kStripeHtmlPage))}';

  Future<void> _redirectToStripe(String sessionId) async {
    final redirectToCheckoutJs = '''
var stripe = Stripe(\'${AppConfig.stripePublishableKey}\');
    
stripe.redirectToCheckout({
  sessionId: '$sessionId'
}).then(function (result) {
  result.error.message = 'Error'
});
''';

    try {
      await _webViewController.evaluateJavascript(redirectToCheckoutJs);
    } on PlatformException catch (e) {
      if (!e.details.contains('JavaScript execution returned a result of an unsupported type')) {
        rethrow;
      }
    }
  }
}

const String kStripeHtmlPage = '''
<!DOCTYPE html>
<html>
<script src="https://js.stripe.com/v3/"></script>
<head><title>Stripe checkout</title></head>
<body>
Loading, please wait...
</body>
</html>
''';
```

In your case the code worked after throwing an error. In my case, the error is thrown, but the page is stuck on the initial html.

**Comment by praharshbhatt** [comment]
So I contacted stripe and got the reason.
The webview we are using has to be served via HTTPS/TLS 1.2 which is different from only initializing Stripe.js.
The actual webview itself you use has to make use of HTTPS.

**Comment by MarcinusX** [comment]
Some of you mentioned that what I showed you in the video/post doesn’t work for Stripe live, and I am sorry to say that it is true. HOWEVER! There is an easy solution to that, basically, we need to have our simple HTML deployed on the Https website and it will still work! I’ve put the same HTML in a [repository](https://github.com/MarcinusX/test1/blob/main/index.html) and deployed it on [GitHub pages](https://marcinusx.github.io/test1/index.html) and it worked on live! I’ve just paid myself 2 PLN 😀 I’m sorry for not checking it on live before publishing.

In fact, the current code is using that and it's working correctly :)

Let me know if it works for you.

**Comment by praharshbhatt** [comment]
This works! Thanks a ton!
